Buyer_homepage:
    pattern:  /
    defaults: { _controller: HarvestCloud\CoreBundle\Controller\Buyer\DefaultController::indexAction }

Buyer_hub_nearby:
    pattern:  /hub/nearby
    defaults: { _controller: HarvestCloudMarketPlaceBuyerBundle:Hub:nearby }

Buyer_hub_show:
    pattern:  /hub/{id}
    defaults: { _controller: HarvestCloudMarketPlaceBuyerBundle:Hub:show }
    requirements:
        id: \d+

Buyer_hub_add:
    pattern:  /hub/{id}/add
    defaults: { _controller: HarvestCloudMarketPlaceBuyerBundle:Hub:add }
    requirements:
        id: \d+
        _method: POST


Buyer_cart_show:
    pattern:  /cart
    defaults: { _controller: HarvestCloud\CoreBundle\Controller\Buyer\CartController::showAction }


Buyer_order:
    pattern:  /order
    defaults: { _controller: HarvestCloudMarketPlaceBuyerBundle:Order:index }

Buyer_order_show:
    pattern:  /order/{id}
    defaults: { _controller: HarvestCloudMarketPlaceBuyerBundle:Order:show }

Buyer_order_cancel:
    pattern:  /order/{id}/cancel
    defaults: { _controller: HarvestCloudMarketPlaceBuyerBundle:Order:cancel }
    requirements:
        id: \d+
        _method: POST

Buyer_order_rate:
    pattern:  /order/{id}/rate/{rating}
    defaults: { _controller: HarvestCloudMarketPlaceBuyerBundle:Order:rate }
    requirements:
        id: \d+
        rating: '[1-5]'
        _method: POST


Buyer_invoice:
    pattern:  /invoice
    defaults: { _controller: HarvestCloudMarketPlaceBuyerBundle:Invoice:index }

Buyer_invoice_show:
    pattern:  /invoice/{id}
    defaults: { _controller: HarvestCloudMarketPlaceBuyerBundle:Invoice:show }

Buyer_invoice_pay_with_stripe:
    pattern:  /invoice/{id}/pay/stripe
    defaults: { _controller: HarvestCloudMarketPlaceBuyerBundle:Invoice:payWithStripe }
    requirements:
        id: \d+
        _method: POST

Buyer_invoice_pay_with_saved_credit_card:
    pattern:  /invoice/{id}/pay/saved-credit-card/{saved_credit_card_id}
    defaults: { _controller: HarvestCloudMarketPlaceBuyerBundle:Invoice:payWithSavedCreditCard }
    requirements:
        id: \d+
        saved_credit_card_id: \d+
        _method: POST


Buyer_seller_show:
    pattern:  /seller/{id}
    defaults: { _controller: HarvestCloudMarketPlaceBuyerBundle:Seller:show }
    requirements:
        id: \d+

Buyer_profile_current:
    pattern:  /profile/current
    defaults: { _controller: HarvestCloudMarketPlaceBuyerBundle:Profile:current }

Buyer_profile:
    pattern:  /profile
    defaults: { _controller: HarvestCloudMarketPlaceBuyerBundle:Profile:index }


Buyer_cart_add_product:
    pattern:  /cart/add-product/{id}/{quantity}
    defaults: { _controller: HarvestCloud\CoreBundle\Controller\Buyer\CartController::addProductAction, quantity: 1 }
    requirements:
        _method: POST


Buyer_checkout_select_pickup_windows_for_collection:
    pattern:  /checkout/select-window/{id}
    defaults: { _controller: HarvestCloud\CoreBundle\Controller\Buyer\CheckoutController::select_pickup_window_for_collectionAction }
    requirements:
        _method: POST

Buyer_checkout_pickup_windows:
    pattern:  /checkout/pickup-windows
    defaults: { _controller: HarvestCloud\CoreBundle\Controller\Buyer\CheckoutController::pickup_windows_for_collectionAction }
    requirements:
        _method: GET

Buyer_checkout_review:
    pattern:  /checkout/review
    defaults: { _controller: HarvestCloud\CoreBundle\Controller\Buyer\CheckoutController::reviewAction }

Buyer_checkout_place_order:
    pattern:  /checkout/place-order
    defaults: { _controller: HarvestCloud\CoreBundle\Controller\Buyer\CheckoutController::place_orderAction }
    requirements:
        _method: POST

Buyer_checkout_complete_paypal:
    pattern:  /checkout/complete-paypal
    defaults: { _controller: HarvestCloudMarketPlaceBuyerBundle:Checkout:complete_paypal }

Buyer_checkout_receipt:
    pattern:  /checkout/thank-you
    defaults: { _controller: HarvestCloud\CoreBundle\Controller\Buyer\CheckoutController::receiptAction }

Buyer_product_show:
    pattern:  /{path}/{id}
    defaults: { _controller: HarvestCloud\CoreBundle\Controller\Buyer\ProductController::showAction }
    requirements:
        path: ".*"
        id: \d+

Buyer_browse:
    pattern:  /{path}
    defaults: { _controller: HarvestCloudMarketPlaceBuyerBundle:Default:browse }
    requirements:
        path: ".*"
